Repository Tuk-AOK/backend-v2, pull requests merged in 2023-05, with the labels that each got.

#3 [feat/#2] User 도메인의 Return 값 구체화
  src/main/java/crepe/backend/domain/project/service/ProjectService.java
  src/main/java/crepe/backend/domain/user/domain/repository/UserRepository.java
  src/main/java/crepe/backend/domain/user/dto/UserCreateInfo.java
  src/main/java/crepe/backend/domain/user/dto/UserInfo.java
  src/main/java/crepe/backend/domain/user/service/UserService.java
Labels: refactor

#8 [fix/#7] L002 단일 로그 정보 조회 return 값 logUuid -> userUuid 변경
  src/main/java/crepe/backend/domain/log/service/LogService.java
Labels: fix

#10 [feat/#9] Project Domain에서 Intro 내용 부분 추가 및 프로젝트 추가, 프로젝트 조회에 Intro 추가
  src/main/java/crepe/backend/domain/project/domain/entity/Project.java
  src/main/java/crepe/backend/domain/project/dto/ProjectCreateRequest.java
  src/main/java/crepe/backend/domain/project/dto/ProjectInfo.java
  src/main/java/crepe/backend/domain/project/service/ProjectService.java
Labels: feat

#12 [refactor/#11] 브랜치 도메인 단일 브랜치 모든 피드백 내용 조회 api 추가, 로그에서 피드백 내용 삭제
  src/main/java/crepe/backend/domain/branch/controller/BranchController.java
  src/main/java/crepe/backend/domain/branch/domain/entity/Branch.java
  src/main/java/crepe/backend/domain/branch/dto/BranchFeedbackInfo.java
  src/main/java/crepe/backend/domain/branch/dto/BranchFeedbackInfoList.java
  src/main/java/crepe/backend/domain/branch/dto/BranchInfo.java
  src/main/java/crepe/backend/domain/branch/service/BranchService.java
  src/main/java/crepe/backend/domain/feedback/domain/entity/Feedback.java
  src/main/java/crepe/backend/domain/feedback/domain/repository/FeedbackRepository.java
  src/main/java/crepe/backend/domain/feedback/dto/FeedbackCreate.java
  src/main/java/crepe/backend/domain/feedback/service/FeedbackService.java
  src/main/java/crepe/backend/domain/log/domain/entity/Log.java
  src/main/java/crepe/backend/domain/log/dto/LogFeedbackInfoList.java
  src/main/java/crepe/backend/domain/log/dto/LogInfo.java
  src/main/java/crepe/backend/domain/log/service/LogService.java
  src/main/java/crepe/backend/global/response/ResultCode.java
Labels: refactor

#16 [Feat/#1] 프로젝트 도메인에 preview 추가
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/crepe/backend/domain/project/domain/entity/Project.java
  src/main/java/crepe/backend/domain/project/dto/ProjectCreateRequest.java
  src/main/java/crepe/backend/domain/project/dto/ProjectInfo.java
  src/main/java/crepe/backend/domain/project/service/ProjectService.java
  src/main/java/crepe/backend/domain/user/controller/UserController.java
Labels: feat
